admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Index:index }

albums:
    path:     /admin/albums
    defaults: { _controller: AdminBundle:Album:index }

albums_new:
    path:   /admin/albums/new
    defaults: { _controller: AdminBundle:Album:new }